server:
  port: 8080

spring:
  profiles:
    active: local

---
spring:
  config:
    active:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: embedded
---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3307/springbatch?useUnicode=true&characterEncoding=utf8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    job:
      #names: batchJob1,batchJob2 # 설정된 이름의 job만을 실행(,구분하여 여러개 가능)
      names: ${job.name:NONE} # Program Arguments 에서 --job.name=batchJob1,batchJob2
      enabled: true # 시스템 시작 시 자동 실행여부
      #enabled: false
    jdbc:
      initialize-schema: always # 시스템 시작 시 스키마 초기화 여부
      #initialize-schema: never
      #table-prefix: SYSTEM_ # 테이블 접미사, 기본은 BATCH_
