services:
  mysql:
    image: mysql:latest
    container_name: spring-batch-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:    
      - 3307:3306
    volumes:
      - "/d/docker/database/mysql/data:/var/lib/mysql"